import { HOOKS, Hook, fillHook, getRandomHook } from './hooks'

export interface ScriptOutput {
  hook: string
  hookId: string
  script: string
  wordCount: number
  estimatedDuration: number
  players: string[]
  teams: string[]
  picks: { team: string; line: string; type: 'spread' | 'total' | 'moneyline' }[]
  title: string
  date: string
}

export interface GenerateInput {
  picks: string[]
  sport: string
  day: string
  date: string
  hookId?: string
  tone?: Hook['tone']
  count: number
}

const SYSTEM_PROMPT = `You are a hype sports betting content creator writing short-form video scripts for @novig, a zero-vig peer-to-peer sports betting app. Your scripts sound like a confident, fast-talking sports personality — think sharp, punchy, and exciting.

Rules:
- Start with the hook provided. Do not change a single word of it.
- Write naturally for a voiceover (no bullet points, no headers)
- Keep total word count between 150-200 words
- Reference specific lines and teams from the picks provided
- End with: "Hit the link in bio and get on Novig — zero vig, all edge."
- Output ONLY valid JSON, no other text

Output this exact JSON structure:
{
  "hook": "<the hook text>",
  "hookId": "<hook id>",
  "script": "<full script starting with hook>",
  "wordCount": <number>,
  "estimatedDuration": <seconds>,
  "players": ["<player names mentioned>"],
  "teams": ["<team names mentioned>"],
  "picks": [
    { "team": "<team>", "line": "<line>", "type": "spread|total|moneyline" }
  ],
  "title": "<auto-generated title e.g. NBA Thursday Picks>",
  "date": "<formatted date>"
}`

export async function generateScript(input: GenerateInput): Promise<ScriptOutput> {
  const hook = input.hookId
    ? HOOKS.find(h => h.id === input.hookId)!
    : getRandomHook({ tone: input.tone })

  const filledHook = fillHook(hook, {
    day: input.day,
    sport: input.sport,
    count: input.count
  })

  const userPrompt = `
Hook (use this EXACTLY as the first line): "${filledHook}"
Hook ID: ${hook.id}
Sport: ${input.sport}
Day: ${input.day}
Date: ${input.date}
Picks:
${input.picks.map((p, i) => `${i + 1}. ${p}`).join('\n')}

Write the full video script now.`

  const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${process.env.OPENROUTER_API_KEY}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      model: 'anthropic/claude-sonnet-4-20250514',
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: userPrompt }
      ],
      temperature: 0.8,
      max_tokens: 2000
    })
  })

  if (!res.ok) {
    const errBody = await res.text()
    throw new Error(`OpenRouter API error ${res.status}: ${errBody}`)
  }

  const data = await res.json()
  const content = data.choices[0].message.content

  const clean = content.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim()
  return JSON.parse(clean)
}
